#Numpy 알아보기
* 대용량의 배열과 행렬 연산을 빠르게 수행합니다.
* 수학 연산자와 함수를 포함하고 있습니다.






1. Numpy 패키지 호출

In [24]:
import numpy as np #as는 앞의 이름을 대체하는 별칭, numpy의 별칭은 np입니다.

2. Numpy 배열 생성
* 넘파이에서 제공하는 array() 함수를 사용합니다.
* array() 함수에 리스트를 넣으면 넘파이 배열이 생성됩니다.

In [25]:
a = np.array([1,2,3])
b = np.array([10,20,30])

3. Numpy 속성
* a.shape   : a 배열의 형태입니다.(각 차원의 원소의 크기)
* a.ndim    : a 배열의 차원입니다.
* a.dtype   : a 배열의 내부 자료형입니다.
* a.size    : a 배열의 전체 크기입니다.(속성의 개수)
* a.itemsize: a 배열의 내부 자료형이 차지하는 메모리 크기(byte)입니다.

In [26]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3,)
1
int64
8
3


4. Numpy 연산

In [27]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[0 0 0]




---






 ## Numpy 함수

1. arrange()
* 넘파이 1차원 배열을 반환합니다.
* 리스트에 range 같은 역할을 합니다.

**numpy.arange(start, stop, step)**

* start의 기본값은 0입니다.
* stop은 데이터의 끝 값으로 배열은 stop-1까지 생성됩니다.
* step은 데이터 생성 간격입니다.

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
print(np.arange(5)) #stop
print(np.arange(0,5)) #start,stop
print(np.arange(0,5,1)) #start,stop,step

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


2. linspace()
* 시작값부터 끝 값까지 균일한 간격, 지정된 개수만큼의 배열을 생성합니다.

**numpy.linspace(start,stop,num)**
* start와 stop 는 데이터 생성을 시작하고 멈추는 값으로 생략할 수 없습니다.
* 배열은 stop-1까지 생성됩니다.
* num은 데이터 생성 개수로 기본값은 50입니다.

In [30]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

3. logspace()
* 로그 스케일로 수를 생성합니다.

**numpy.logspace(start,stop,num)**
* start와 stop은 똑같이 생략할 수 없습니다.
* 데이터 생성은 $10^{start}$에서 시작하고 $10^{stop}$에서 멈춥니다.
* 데이터 생성 개수도 50입니다.

In [31]:
np.logspace(1,2)

array([ 10.        ,  10.48113134,  10.98541142,  11.51395399,
        12.06792641,  12.64855217,  13.25711366,  13.89495494,
        14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
        17.57510625,  18.42069969,  19.30697729,  20.23589648,
        21.20950888,  22.22996483,  23.29951811,  24.42053095,
        25.59547923,  26.82695795,  28.11768698,  29.47051703,
        30.88843596,  32.37457543,  33.93221772,  35.56480306,
        37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
        44.98432669,  47.14866363,  49.41713361,  51.79474679,
        54.28675439,  56.89866029,  59.63623317,  62.50551925,
        65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
        79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
        95.40954763, 100.        ])

4. reshape()
* 데이터의 개수는 유지한 상태로 차원과 형태를 변형합니다.
* 원래 배열(n,m)이고 변형하는 형태가 (l,k)라 할 때, $n\times m = l\times k$을 만족해야합니다.

In [32]:
c = np.arange(15) # 1차원 배열 생성
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
c.reshape(3,5) # 배열은 3X5 형태로 변형

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
#오류 케이스
c.reshape(3,4) # 3X4는 12이므로 처음 배열 크기인 15와 맞지 않습니다.

ValueError: cannot reshape array of size 15 into shape (3,4)

5. flatten()
* 2차원 이상의 배열을 1차원 배열로 변환합니다.

In [36]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Numpy 인덱싱&슬라이싱
* 리스트와 마찬가지로 인덱스를 이용하여 특정한 요소를 추출할 수 있습니다.
* 인덱스의 시작은 0입니다.
* 인덱스에 음수도 적용됩니다.

**numpy_array[start:end:step]**
* 슬라이싱시 start부터, end까지 step만큼 간격으로 슬라이싱 합니다.
* step의 기본값은 1입니다.

1. 기본 슬라이싱,인덱싱 확인

In [55]:
temp = np.arange(10,110,10) # 10부터 100까지 들어있는 넘파이 배열 생성
temp

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [48]:
print(temp[0])
print(temp[-1])
print(temp[1:3])
print(temp[-8:-6])

10
100
[20 30]
[30 40]


2. 논리 인덱싱
* 어떠한 조건을 입력하여 배열에서 원하는 값을 얻을 수 있습니다.

In [58]:
 lo = temp > 30 # 넘파이 배열(temp)에서 30 이상만 골라내는 조건식
 lo # 조건의 결과를 확인합니다.

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [59]:
temp[temp > 30] #필요한 결과만 뽑기 위해 다음과 같이 작성해줍니다.

array([ 40,  50,  60,  70,  80,  90, 100])

3. 2차원 배열 인덱싱
* 2차원 배열은 2개의 인덱스가 필요합니다.
* 앞의 인덱스는 행의 번호, 뒤에는 열의 번호입니다.
* 리스트에서는 [n][m]라는 형태를 가졌다면 넘파이에서는 [n,m]의 형태를 가집니다.

In [63]:
temp2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 2차원 넘파이 배열 생성
temp2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
temp2[0] # 첫 번째 인덱스만 지정했으므로 0번째 행 전부 다 출력

array([1, 2, 3])

In [65]:
temp2[0,2] # 첫 번째 인덱스가 0이고 2번째 인덱스가 2이므로 3이라는 결과 도출

3

* 슬라이싱과 합쳐서 다음과 같이 응용할 수 있습니다.

In [75]:
temp2[2,0:2] # 2번째 행에서 0-1번째 열까지 출력

array([7, 8])

4. 2차원 배열 논리 인덱싱
* 2차원 배열에서도 주어진 조건에 따라서 요소를 추출할 수 있습니다.

In [77]:
temp2 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [81]:
temp2[temp2 > 5] # temp2 넘파이 배열에서 5 이상의 수만 추출하기

array([6, 7, 8, 9])

In [80]:
temp2[temp2%2==0] # temp2 넘파이 배열에서 짝수만 추출하기

array([2, 4, 6, 8])